### ISSUE TITLE
(dev-branch) Model Explorer not loading without page refresh

### ISSUE THREAD

**Issue by stevebus** [Azure-Samples/digital-twins-explorer#104] opened 2021-03-05 17:40 UTC
I start with an empty ADT instance and then upload a set of model files.  If I go straight to the Model View tab, nothing shows up.  The model will only show up after I refresh the entire ADT-Explorer web page with the browser refresh button.  I would expect viewing a newly uploaded model to work without a page refresh

![image](https://user-images.githubusercontent.com/11857454/110152464-66a48300-7da7-11eb-87f3-8ff49ae02a63.png)

**Comment by jamiewilbraham** [comment] 2021-03-18 02:43
Hi @stevebus ,

I have tried to reproduce this issue without much luck. 

Steps:
1. Empty ADT instance.
2. Upload multiple models via bulk import.
3. Graph reloaded as expected.

Just wanted to check a few things:
- What browser are you using?
- Have you pulled the latest from develop?


Thanks for the additional info!

**Comment by stevebus** [comment] 2021-03-18 16:14
Hey @jamiewilbraham  - I just duplicated it again..  In my pull of the development branch, I did a git pull to bring it up to date, ran npm install again, and then ran it..

I created a completely fresh ADT instance, launched ADT Explorer from my dev branch, imported the same model files, immediately clicked on "model view"  (not graph)  without doing anything else and got a blank screen again.

I'm using Microsoft Edge as the browser.   I also heard from another member of the ADT team who has the same experience.

You said above "Graph loaded as expected" -- to confirm, you mean the 'model' graph right (without running any queries), not the twin instance graph.

![image](https://user-images.githubusercontent.com/11857454/111659049-e3d5ec00-87da-11eb-83ec-45a3cc2de827.png)

**Comment by stevebus** [comment] 2021-03-18 16:16
As an aside, as mentioned above, after hitting the "Refresh" button in the browser, the model view loads

![image](https://user-images.githubusercontent.com/11857454/111659689-6eb6e680-87db-11eb-8568-20b57210f1c0.png)

**Comment by jamiewilbraham** [comment] 2021-03-19 00:53
Hi @stevebus,

Thanks for providing this additional information. Yes, I was referring to the model graph. However, I have since been able to reproduce the issue, so thanks for reporting it.

After the initial load of models in the instance (which doesn't load the nodes on the model graph), if you delete all the models and then repeat the steps (without a refresh), do you still get the issue?

I would just like to confirm if this is specific to fresh ADT instances.

Thanks for your help!

**Comment by stevebus** [comment] 2021-03-19 14:22
Hey @jamiewilbraham  --   I deleted all the models and then imported a fresh set of models (I picked a different set to avoid any potential caching benefits).  I then went straight to the model view and it worked fine!   So it looks like it might be just related to a totally fresh ADT instance, as you suspect.

![image](https://user-images.githubusercontent.com/11857454/111794730-87cf9e00-8894-11eb-8934-19feaa6509fc.png)

**Comment by jamiewilbraham** [comment] 2021-03-21 23:57
Great - thanks for confirming @stevebus! We are looking into it.

**Comment by jamiewilbraham** [comment] 2021-03-25 01:40
@stevebus - this should now be fixed in the development branch

**Comment by jamiewilbraham** [comment] 2021-04-07 23:51
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!

**Closed by jamiewilbraham** 2021-04-07 23:51 UTC
Labels: bug, fixed in development branch
