### ISSUE TITLE
List of elements of `InterfaceB` in a definition of `InterfaceA`  for "elementSchema" of a schema with "@type": "Array" not supported

### ISSUE THREAD

**Issue by simonpfeifhofer** [Azure-Samples/digital-twins-explorer#88] opened 2021-01-05 14:44 UTC
According to the dtdl v2 specification 
- a complex schema can be used e.g. for `elementSchema` of a schema with `"@type":"Array"` but
- an existing `Interface` cannot be used as complex schema.

This restriction leads to not beeing able to create a list of items which are of a defined `Interface`. Interfaces can be combined and reused using `"@type": "Component"`, however it's not possible to create a list.

**It's designed in that manner to force the usage of `Relationship` in that case?
Is there any best-practice for the necessity to include a list of 0-n items of an `Interface` in another `Interface`?
Are there any plans to support it?**

Tested it with:
- digital-twin-explorer and 
- [DTDL-Vaidator](https://github.com/Azure-Samples/DTDL-Validator/)

In order to reproduce the following model can be used:

```
[
  {
    "@context": "dtmi:dtdl:context;2",
    "@id": "dtmi:com:example:TestRoot;1",
    "@type": "Interface",
    "displayName": "TestRoot",
    "contents": [
      {
        "@type": "Property",
        "name": "Prop1",
        "schema": "string"
      },
      {
        "@type": "Telemetry",
        "name": "TelementryArray",
        "schema": {
          "@type": "Array",
          "elementSchema": "dtmi:com:example:TestElement;1"
        },
        {
        "@type": "Relationship",
        "name": "TestElements",
        "minMultiplicity": 0,
        "maxMultiplicity": 1,
        "target": "dtmi:com:example:TestElement;1"
        },
      }
    ]
  },
  {
    "@context": "dtmi:dtdl:context;2",
    "@id": "dtmi:com:example:TestElement;1",
    "@type": "Interface",
    "displayName": "TestElement",
    "contents": [
      {
        "@type": "Property",
        "name": "Base64String",
        "schema": "string",
        "displayName": "Value",
        "description": "Base64 encoded value"
      }
    ]
  }
]
```

The following error occurs:
```
Upload error: RestError: None of the models in this request could be created due to a problem with one or more models: dtmi:com:example:TestRoot;1 has 'contents' value with name 'TelementryArray' which has 'schema' value whose property 'elementSchema' has value dtmi:com:example:TestElement;1 that does not have @type of Array, Enum, Map, or Object, nor is it a standard value for this property. 
Provide a value for property 'elementSchema' with @type in the set of allowable types, or choose one of the following values for property 'elementSchema': boolean, string, double, float, long, integer, date, dateTime, duration, time.. 
See model documentation(http://aka.ms/ADTv2Models) for supported format.
```

**Comment by cschormann** [comment] 2021-01-27 23:51
Yes, in DTDL the way to create a 1:many relationship (list of referenced items, or the equivalent of List<> in C#) is to use a relationship. 
Adt-explorer (and the underlying ADT instance) just follows the DTDL spec in this. 

As this is by design, I will close this item. Please get back to us if you would like to discuss this further.

**Closed by cschormann** 2021-01-27 23:51 UTC
Labels: question
